### PR TITLE
Add Oracle 7 / 8 / 9

### PR DESCRIPTION
**Pull request by davidjkling**
Added Oracle Platforms:
7
8
9

each based on a corresponding [bento](https://app.vagrantup.com/bento) box

### CODE REVIEW

**Comment by ramereth** [comment]
@davidjkling I think they've been opting to move away from having point releases and instead just having the major release (i.e. `7.json` and `8.json`). Could you please refactor your PR to do that?

**Comment by davidjkling** [comment]
@ramereth updated, as well as adding in OL 9.

**Review by tpowell-progress — APPROVED** [review]

**Review by jaymzh — APPROVED** [review]

**Comment by ramereth** [comment]
@davidjkling I just got the following word from Chef via Slack:

> Please note, fauxhai ruby gem is being published from the [chef/fauxhai](https://github.com/chef/fauxhai) fork since last year. this was done as we had lost access/ contact to original chefspec org.

**Comment by davidjkling** [comment]
> @davidjkling I just got the following word from Chef via Slack:
> 
> > Please note, fauxhai ruby gem is being published from the [chef/fauxhai](https://github.com/chef/fauxhai) fork since last year. this was done as we had lost access/ contact to original chefspec org.

Thanks for that, will move this to the new fork.

**Comment by davidjkling** [comment]
Was moved to [chef#12](https://github.com/chef/fauxhai/pull/12)

**Pull request closed without merging**
