### PR TITLE
fixing debian versions

### PR DESCRIPTION
**Pull request by shashaa35**

### CODE REVIEW

**Comment by tas50** [comment]
This is actually correct. Debian isn't distinguishing between the releases anymore. There isn't really a 9.1 vs. 9.2. It's just 9 at a different date.

**Comment by shashaa35** [comment]
Then, why there are different jsons for different versions?

**Comment by tas50** [comment]
Historically we had versions for each release. I didn't realize in the 9.x timeline that Debian had moved away from the major.minor version releases so we ended up with multiple JSON dumps. Moving forward I've stopped making dumps for each minor release. It makes the Fauxhai release pretty huge on disk and provides pretty limited value. Debian 10 is a good example of this as is SLES 15.

**Comment by shashaa35** [comment]
Ok.. Seems justified.
Thanks for the response.

**Pull request closed without merging**
